### ISSUE TITLE
How to programitically change route and screen ?

### ISSUE THREAD

**Issue by anuragvohraec** [mobily-enterprises/routify#1]
Hi team,

How do we programmitically change the route ?
For example :
`window.routify.goTo('/myPage')`
And it shoudl activate the mypage element ?

Use case: I have flash screen in my app, which wanted to move away after n number of seconds.
Or bind a page on a button click event.

**Comment by anuragvohraec** [comment]
Ok going through the source code I came to know this :
```
window.history.pushState({}, '', '/path/where/to/go');
window.dispatchEvent(new PopStateEvent('popstate'));
```
this will do the trick. But not sure if it will preserev the state.
Is there any official way [method] to do this ?

**Comment by mercmobily** [comment]
Good question, and it should go to the FAQ.
You would need to do this:

    function goTo(path) {
      window.history.pushState({}, '', path)
      window.dispatchEvent(new PopStateEvent('popstate', {}))
    }

Basically, you will first change the path with pushState, and then
artificially emit a popstate event -- which will trigger routify.

Please confirm that the code above works 100%. I will add this to the
documentation.

Also, I _really_ encourage you to use historify to add proper history
management in your app. I am sure you will love it!

https://www.npmjs.com/package/historify

Merc.

**Comment by mercmobily** [comment]
Well this is actually the official way to do this; this is by using basic
Browser abilities.

What do you mean by "preserve the state"?

**Comment by anuragvohraec** [comment]
> What do you mean by "preserve the state"?

Well I mean, as it pushes something on stack, will it preserve proper forward and backward button functionality, if I randomly push a route in the history stack.
I am not very expert in this field, but from a general glance I guessed that some how stacks of hostory is maintained, and pushing on it will solve the problem.

Thank you for providing the exact code.
Can we please also add this method in the official api , may be in future releases ?

**Comment by anuragvohraec** [comment]
> Please confirm that the code above works 100%.

Yup, its working.

**Comment by mercmobily** [comment]
Hi,

I agree it's a very common method.
I will add it tonight.

How do you manage history in your application?  Have you looked at
historify?

Merc.

**Comment by anuragvohraec** [comment]
> Hi, I agree it's a very common method. I will add it tonight.

Thank you!

> How do you manage history in your application? Have you looked at historify?

Not yet, I will gradually.
I am desinging my app from scratch [no framework, purely web components], so gradually I faced a problem of routing and then I came accross your solution.

Eventually I need history too in app, so will use it once my app start taking shape.

**Comment by mercmobily** [comment]
Hi,

Are you using recommendations from https://open-wc.org/?
If not, I _really_ recommend it!
lit-html is also very amazing.

Merc.

**Comment by mercmobily** [comment]
Wait... I haven't yet added that method. I will do it soon, I promise. Reopening!
